spring.application.name=smart-support-dashboard

# CONFIGURACIÓN DE BASE DE DATOS
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Solución para compatibilidad (Supabase / Postgres)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# IA - CONFIGURACIÓN DE GEMINI
gemini.api.key=${GEMINI_API_KEY:no_key_provided}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# JWT Config
app.jwt.secret=${JWT_SECRET_APP:super_secret_key_that_is_very_very_long_to_satisfy_the_hmac_sha_256_algorithm_requirements_9876543210}
jwt.expirationMs=86400000

# Solución para error "prepared statement already exists" (PgBouncer/Supabase)
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# SUPABASE STORAGE
supabase.url=${SUPABASE_URL:https://no-url-provided.supabase.co}
supabase.key=${SUPABASE_KEY:no_key_provided}

# RESEND EMAIL API
resend.api.key=${RESEND_API_KEY:no_key_provided}
resend.from.email=onboarding@resend.dev
