spring.application.name=smart-support-dashboard
# Puerto donde correrÃ¡ nuestra API
server.port=8080

# ConfiguraciÃ³n de la base de datos en memoria (H2)
spring.datasource.url=jdbc:h2:mem:ticketdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate (La herramienta que convierte clases Java a tablas SQL)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola web de H2 para ver los datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuración de Google Gemini API
gemini.api.key=AIzaSyD1Bd6VsmVUJ8vmRCuboUsCeIbsBAwSrTs
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
